version: "1.13-1.0"
enable_durability: true
require_hoe_for_planting: true
require_tool_for_breaking: true
weapons:
  diamond_sword: 7
  iron_sword: 6
  stone_sword: 5
  golden_sword: 4
  wooden_sword: 4
plants:
  oak_sapling/oak_sapling:
      - 'dirt'
      - 'grass_block'
  spruce_sapling/spruce_sapling:
      - 'dirt'
      - 'grass_block'
  birch_sapling/birch_sapling:
      - 'dirt'
      - 'grass_block'
  jungle_sapling/jungle_sapling:
      - 'dirt'
      - 'grass_block'
  acacia_sapling/acacia_sapling:
      - 'dirt'
      - 'grass_block'      
  dark_oak_sapling/dark_oak_sapling:
      - 'dirt'
      - 'grass_block'
  carrots/carrot:
      - 'farmland'
  potatoes/potato:
      - 'farmland'
  pumpkin_stem/pumpkin_seeds:
      - 'farmland'
  melon_stem/melon_seeds:
      - 'farmland'
  beetroots/beetroot_seeds:
      - 'farmland'
  wheat/wheat_seeds:
      - 'farmland'
  nether_wart/nether_wart:
      - 'soul_sand'
  chorus_flower/chorus_flower:
      - 'end_stone'
hoes:
    - 'diamond_hoe'
    - 'golden_hoe'
    - 'iron_hoe'
    - 'stone_hoe'
    - 'wooden_hoe'
tools:
    - 'diamond_pickaxe'
    - 'iron_pickaxe'
    - 'golden_pickaxe'
    - 'stone_pickaxe'
    - 'wooden_pickaxe'
    - 'diamond_axe'
    - 'iron_axe'
    - 'wooden_axe'
    - 'stone_axe'
    - 'golden_axe'
    - 'diamond_shovel'
    - 'iron_shovel'
    - 'golden_shovel'
    - 'stone_shovel'
    - 'wooden_shovel'    
arthropods:
    - 'spider'
    - 'cave_spider'
    - 'silverfish'
    - 'endermite'
undead:
    - 'zombie'
    - 'skeleton'
    - 'stray'
    - 'wither'
    - 'wither_skeleton'
    - 'husk'
    - 'zombie_villager'
    - 'pig_zombie'
    - 'drowned'
    - 'phantom'
    - 'skeleton_horse'
    - 'zombie_horse'